# Created 2014 by Mazama Science
# 
# Makefile to convert IDB population data.


################################################################################
# Targets 

all: convertMidYearPop

convertMidYearPop: FORCE
	R --slave -f convertMidYearPop.R


FORCE:

